# If a value is commented out, it should be the default.
# See https://github.com/JohnnyMorganz/StyLua

######################################################################
# All possible configuration options
######################################################################
# syntax = "All"
column_width = 80
# line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
# quote_style = "AutoPreferDouble"
# call_parentheses = "Always"
# space_after_function_names = "Never"
collapse_simple_statement = "Always"

[sort_requires]
enabled = true
