line-length = 80
[format]
skip-magic-trailing-comma = true

[lint]
flake8-annotations.mypy-init-return = true
select = ["ALL"]
ignore = ["ERA001", # Commented out code
    "T201", # print
    "D100", # Missing docstrings
    "D101", # .
    "D102", # .
    "D103",
    # # "D104", # .
    "D105", # .
    # # "D106", # .
    # "D107", # .
    # "D206",
    # "D300",
    "N803", # Variables lowercase
    "N806", # .

    # For formatting, see
    # https://docs.astral.sh/ruff/formatter/#format-suppression:
    "W191",
    "E111",
    "E114",
    "E117",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
    "PLR2004", # Magic value in comparison
    "S311", # Random numbers bad for cryptography
    "E731", # Allow assigning to lambda expressions
]

fixable = ["ALL"]
unfixable = ["F401"] # Don't remove unused imports



[lint.pydocstyle]
convention = "numpy"
